services:
  shell:
    build: ./shell
    ports:
      - "3001:3001"
    environment:
      - REMOTE_NEXT_APP_URL=http://localhost:3002
      - NEXTAUTH_URL=http://localhost:5000
  mfe:
    build: ./mfe
    ports:
      - "3002:3002"
  api:
    build: ./back-tech-challenge-2
    ports:
      - "5000:5000"
