name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - '"thiago/docker-compose-and-gke-configurations"'

env:
  PROJECT_ID: 'my-project' # TODO: update to your Google Cloud project ID
  GAR_LOCATION: 'us-central1' # TODO: update to your region
  GKE_CLUSTER: 'cluster-1' # TODO: update to your cluster name
  GKE_ZONE: 'us-central1-c' # TODO: update to your cluster zone
  DEPLOYMENT_NAME: 'gke-test' # TODO: update to your deployment name
  REPOSITORY: 'samples' # TODO: update to your Artifact Registry docker repository name
  IMAGE: 'static-site'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider' # TODO: update to your workload identity provider

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Build and push Docker container'
        run: |-
          echo "${PROJECT_ID}"
          echo "${GAR_LOCATION}"
          echo "${GKE_CLUSTER}"
          echo "${WORKLOAD_IDENTITY_PROVIDER}"
          echo "${REPOSITORY}"
          echo "${GKE_ZONE}"
