name: 'Build and Deploy to GKE'

on:
  push:
    branches: ["main", "thiago/docker-compose-and-gke-configurations"]

env:
  APP: 'shell'
  TAG: '123'
  GKE_SA: ${{ secrets.GKE_SA }}
  CLUSTER: 'fiap-tech-challenge-fase-2'
  PROJECT_ID: 'fiap-fe-tech-challenge-fase-2'
  DOCKER_IMAGE: "gcr.io/fiap-fe-tech-challenge-fase-2/shell:123"
  SUBDOMAIN: "fase-2-shell.challengecoders.com"

jobs:
  setup-build-publish-deploy:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GKE_SA }}
        project_id: ${{ env.PROJECT_ID }}

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GKE_SA }}

    - name: Publish Docker Image'
      run: |-
        docker build -t "$APP" -f "./$APP/k8s/Dockerfile" "./$APP"
        docker tag "$APP" "gcr.io/$PROJECT_ID/$APP:$TAG"
        gcloud --quiet auth configure-docker
        docker push "gcr.io/$PROJECT_ID/$APP:$TAG"
